apiVersion: apps/v1
kind: Deployment
metadata:
  name: kisan-market
  labels:
    app: kisan-market
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kisan-market
  template:
    metadata:
      labels:
        app: kisan-market
    spec:
      containers:
        - name: kisan-market
          image: kisan-market:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
